### ISSUE TITLE
Black screen is show on pushing view controller

### ISSUE THREAD

**Issue by suriForIOS** [asisadh/NavigationDrawerSwift#1]
Black screen is show on pushing view controller from the sliding menu screen in swift 5.1.

**Comment by ProKashif** [comment]
You can resolve your bug by replacing presentation style with full Screen in a storyboard

**Comment by asisadh** [comment]
For anyone having the same issue, you can change the model presentation style to `fullScreen`

destinationViewController.modalPresentationStyle = .fullScreen
