### ISSUE TITLE
Navigation drawer at Right

### ISSUE THREAD

**Issue by milindrc** [asisadh/NavigationDrawerSwift#3]
How to change the behaviour to show this navigation drawer at right side?

**Comment by asisadh** [comment]
To make the navigation drawer at right.

```
func animationController(forPresented presented: UIViewController, presenting: UIViewController, source: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        return PresentMenuAnimator(direction: .Right)
    }
```

add direction in presentation menu animator.

PS. also adjust your closing button respectively to the left of the screen as in the demo which has closing button on the right side of screen.
